// Code generated by cppgo from the AST of Quantum::Physics::PhonoEngine. DO NOT EDIT.

package phono

/*
#cgo CXXFLAGS: -std=c++17

// The C++ runtime is linked automatically by the go tool for packages
// containing .cpp files; naming it here would duplicate it.
#include <stdlib.h>
#include "bridge.h"
*/
import "C"

import (
	"errors"
	"runtime"
	"sync"
)

// PhonoEngine is a Go handle to a native Quantum::Physics::PhonoEngine.
//
// The C++ instance is allocated on the native heap and reached only through
// the opaque PhonoEngineHandle token, so the Go collector never scans, moves or
// traces into it.
//
// The zero value is not usable and a value of this type must never be
// copied: a copy would duplicate ownership of a handle that is destroyed
// exactly once. Always pass the pointer returned by a constructor.
type PhonoEngine struct {
	// mu guards handle against a concurrent Close, which would otherwise
	// race a method call into a use-after-free.
	mu     sync.RWMutex
	handle C.PhonoEngineHandle
}

// ErrPhonoEngineAllocation reports that the native constructor could not allocate.
// The bridge allocates with `new (std::nothrow)`, so an exhausted heap
// surfaces as a null handle rather than a std::bad_alloc unwinding into
// the Go runtime.
var ErrPhonoEngineAllocation = errors.New("cppgo: Quantum::Physics::PhonoEngine: native allocation failed")

// NewPhonoEngine allocates a native Quantum::Physics::PhonoEngine.
//
// C++ signature: Quantum::Physics::PhonoEngine::PhonoEngine(int, int, int, double, double, double, double, double, int)
//
// The returned wrapper carries a finalizer, so a caller that drops it
// without calling Close still releases the native object once the
// collector observes the wrapper is unreachable.
func NewPhonoEngine(width int, height int, depth int, dx float64, dy float64, dz float64, hbar float64, mass float64, maxWorkers int) (*PhonoEngine, error) {

	handle := C.quantum_physics_PhonoEngine_Create(C.int(width), C.int(height), C.int(depth), C.double(dx), C.double(dy), C.double(dz), C.double(hbar), C.double(mass), C.int(maxWorkers))
	if handle == nil {
		return nil, ErrPhonoEngineAllocation
	}

	obj := &PhonoEngine{handle: handle}
	runtime.SetFinalizer(obj, (*PhonoEngine).finalize)
	return obj, nil
}

// Close destroys the underlying Quantum::Physics::PhonoEngine and releases its
// native memory.
//
// Close is idempotent and safe to call concurrently with any other method.
// It is the deterministic release path and should be preferred: the Go
// runtime guarantees only that a finalizer runs at some point after the
// object becomes unreachable, and makes no guarantee at all that one runs
// before the process exits.
func (p *PhonoEngine) Close() {
	if p == nil {
		return
	}
	p.mu.Lock()
	defer p.mu.Unlock()
	if p.handle == nil {
		return
	}

	C.quantum_physics_PhonoEngine_Destroy(p.handle)
	p.handle = nil
	// The native object is gone; retract the finalizer so the runtime has
	// no reason to keep the wrapper alive for an extra collection cycle.
	runtime.SetFinalizer(p, nil)
}

// Valid reports whether the wrapper still owns a live native object.
func (p *PhonoEngine) Valid() bool {
	if p == nil {
		return false
	}
	p.mu.RLock()
	defer p.mu.RUnlock()
	return p.handle != nil
}

// finalize is installed by every constructor via runtime.SetFinalizer. It
// is the garbage collector's entry point into the native heap: when the
// wrapper becomes unreachable without an explicit Close, the collector
// invokes this and the flat C destructor runs `delete` on the C++ object.
//
// It executes on the runtime's dedicated finalizer goroutine. Nothing can
// hold a reference at that point, so the lock is uncontended and is taken
// only to publish the nil write.
func (p *PhonoEngine) finalize() {
	p.mu.Lock()
	defer p.mu.Unlock()
	if p.handle != nil {
		C.quantum_physics_PhonoEngine_Destroy(p.handle)
		p.handle = nil
	}
}

// Initialize wraps bool Quantum::Physics::PhonoEngine::Initialize().
//
// Returns false if the wrapper has already been closed.
func (p *PhonoEngine) Initialize() bool {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return false
	}

	cRet := C.quantum_physics_PhonoEngine_Initialize(p.handle)
	return cRet != 0
}

// Ready wraps bool Quantum::Physics::PhonoEngine::Ready() const.
//
// Returns false if the wrapper has already been closed.
func (p *PhonoEngine) Ready() bool {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return false
	}

	cRet := C.quantum_physics_PhonoEngine_Ready(p.handle)
	return cRet != 0
}

// Width wraps int Quantum::Physics::PhonoEngine::Width() const.
//
// Returns int(0) if the wrapper has already been closed.
func (p *PhonoEngine) Width() int {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return int(0)
	}

	return int(C.quantum_physics_PhonoEngine_Width(p.handle))
}

// Height wraps int Quantum::Physics::PhonoEngine::Height() const.
//
// Returns int(0) if the wrapper has already been closed.
func (p *PhonoEngine) Height() int {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return int(0)
	}

	return int(C.quantum_physics_PhonoEngine_Height(p.handle))
}

// Depth wraps int Quantum::Physics::PhonoEngine::Depth() const.
//
// Returns int(0) if the wrapper has already been closed.
func (p *PhonoEngine) Depth() int {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return int(0)
	}

	return int(C.quantum_physics_PhonoEngine_Depth(p.handle))
}

// Size wraps int Quantum::Physics::PhonoEngine::Size() const.
//
// Returns int(0) if the wrapper has already been closed.
func (p *PhonoEngine) Size() int {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return int(0)
	}

	return int(C.quantum_physics_PhonoEngine_Size(p.handle))
}

// MaxWorkers wraps int Quantum::Physics::PhonoEngine::MaxWorkers() const.
//
// Returns int(0) if the wrapper has already been closed.
func (p *PhonoEngine) MaxWorkers() int {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return int(0)
	}

	return int(C.quantum_physics_PhonoEngine_MaxWorkers(p.handle))
}

// Dx wraps double Quantum::Physics::PhonoEngine::Dx() const.
//
// Returns float64(0) if the wrapper has already been closed.
func (p *PhonoEngine) Dx() float64 {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return float64(0)
	}

	return float64(C.quantum_physics_PhonoEngine_Dx(p.handle))
}

// Dy wraps double Quantum::Physics::PhonoEngine::Dy() const.
//
// Returns float64(0) if the wrapper has already been closed.
func (p *PhonoEngine) Dy() float64 {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return float64(0)
	}

	return float64(C.quantum_physics_PhonoEngine_Dy(p.handle))
}

// Dz wraps double Quantum::Physics::PhonoEngine::Dz() const.
//
// Returns float64(0) if the wrapper has already been closed.
func (p *PhonoEngine) Dz() float64 {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return float64(0)
	}

	return float64(C.quantum_physics_PhonoEngine_Dz(p.handle))
}

// Hbar wraps double Quantum::Physics::PhonoEngine::Hbar() const.
//
// Returns float64(0) if the wrapper has already been closed.
func (p *PhonoEngine) Hbar() float64 {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return float64(0)
	}

	return float64(C.quantum_physics_PhonoEngine_Hbar(p.handle))
}

// Mass wraps double Quantum::Physics::PhonoEngine::Mass() const.
//
// Returns float64(0) if the wrapper has already been closed.
func (p *PhonoEngine) Mass() float64 {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return float64(0)
	}

	return float64(C.quantum_physics_PhonoEngine_Mass(p.handle))
}

// CellVolume wraps double Quantum::Physics::PhonoEngine::CellVolume() const.
//
// Returns float64(0) if the wrapper has already been closed.
func (p *PhonoEngine) CellVolume() float64 {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return float64(0)
	}

	return float64(C.quantum_physics_PhonoEngine_CellVolume(p.handle))
}

// PsiRealAddress wraps size_t Quantum::Physics::PhonoEngine::PsiRealAddress() const.
//
// Returns uint(0) if the wrapper has already been closed.
func (p *PhonoEngine) PsiRealAddress() uint {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return uint(0)
	}

	return uint(C.quantum_physics_PhonoEngine_PsiRealAddress(p.handle))
}

// PsiImagAddress wraps size_t Quantum::Physics::PhonoEngine::PsiImagAddress() const.
//
// Returns uint(0) if the wrapper has already been closed.
func (p *PhonoEngine) PsiImagAddress() uint {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return uint(0)
	}

	return uint(C.quantum_physics_PhonoEngine_PsiImagAddress(p.handle))
}

// PotentialAddress wraps size_t Quantum::Physics::PhonoEngine::PotentialAddress() const.
//
// Returns uint(0) if the wrapper has already been closed.
func (p *PhonoEngine) PotentialAddress() uint {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return uint(0)
	}

	return uint(C.quantum_physics_PhonoEngine_PotentialAddress(p.handle))
}

// DensityAddress wraps size_t Quantum::Physics::PhonoEngine::DensityAddress() const.
//
// Returns uint(0) if the wrapper has already been closed.
func (p *PhonoEngine) DensityAddress() uint {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return uint(0)
	}

	return uint(C.quantum_physics_PhonoEngine_DensityAddress(p.handle))
}

// XLineCount wraps int Quantum::Physics::PhonoEngine::XLineCount() const.
//
// Returns int(0) if the wrapper has already been closed.
func (p *PhonoEngine) XLineCount() int {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return int(0)
	}

	return int(C.quantum_physics_PhonoEngine_XLineCount(p.handle))
}

// YBlockCount wraps int Quantum::Physics::PhonoEngine::YBlockCount() const.
//
// Returns int(0) if the wrapper has already been closed.
func (p *PhonoEngine) YBlockCount() int {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return int(0)
	}

	return int(C.quantum_physics_PhonoEngine_YBlockCount(p.handle))
}

// ZBlockCount wraps int Quantum::Physics::PhonoEngine::ZBlockCount() const.
//
// Returns int(0) if the wrapper has already been closed.
func (p *PhonoEngine) ZBlockCount() int {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return int(0)
	}

	return int(C.quantum_physics_PhonoEngine_ZBlockCount(p.handle))
}

// PrepareStep wraps void Quantum::Physics::PhonoEngine::PrepareStep(double).
//
// Does nothing if the wrapper has already been closed.
func (p *PhonoEngine) PrepareStep(dt float64) {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return
	}

	C.quantum_physics_PhonoEngine_PrepareStep(p.handle, C.double(dt))
}

// MarkPotentialDirty wraps void Quantum::Physics::PhonoEngine::MarkPotentialDirty().
//
// Does nothing if the wrapper has already been closed.
func (p *PhonoEngine) MarkPotentialDirty() {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return
	}

	C.quantum_physics_PhonoEngine_MarkPotentialDirty(p.handle)
}

// ApplyPotentialHalfStep wraps void Quantum::Physics::PhonoEngine::ApplyPotentialHalfStep(int, int).
//
// Does nothing if the wrapper has already been closed.
func (p *PhonoEngine) ApplyPotentialHalfStep(begin int, end int) {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return
	}

	C.quantum_physics_PhonoEngine_ApplyPotentialHalfStep(p.handle, C.int(begin), C.int(end))
}

// SweepX wraps void Quantum::Physics::PhonoEngine::SweepX(int, int, int).
//
// Does nothing if the wrapper has already been closed.
func (p *PhonoEngine) SweepX(worker int, begin int, end int) {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return
	}

	C.quantum_physics_PhonoEngine_SweepX(p.handle, C.int(worker), C.int(begin), C.int(end))
}

// SweepY wraps void Quantum::Physics::PhonoEngine::SweepY(int, int, int).
//
// Does nothing if the wrapper has already been closed.
func (p *PhonoEngine) SweepY(worker int, begin int, end int) {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return
	}

	C.quantum_physics_PhonoEngine_SweepY(p.handle, C.int(worker), C.int(begin), C.int(end))
}

// SweepZ wraps void Quantum::Physics::PhonoEngine::SweepZ(int, int, int).
//
// Does nothing if the wrapper has already been closed.
func (p *PhonoEngine) SweepZ(worker int, begin int, end int) {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return
	}

	C.quantum_physics_PhonoEngine_SweepZ(p.handle, C.int(worker), C.int(begin), C.int(end))
}

// StepTime wraps void Quantum::Physics::PhonoEngine::StepTime(double).
//
// Does nothing if the wrapper has already been closed.
func (p *PhonoEngine) StepTime(dt float64) {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return
	}

	C.quantum_physics_PhonoEngine_StepTime(p.handle, C.double(dt))
}

// ComputeDensity wraps void Quantum::Physics::PhonoEngine::ComputeDensity(int, int).
//
// Does nothing if the wrapper has already been closed.
func (p *PhonoEngine) ComputeDensity(begin int, end int) {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return
	}

	C.quantum_physics_PhonoEngine_ComputeDensity(p.handle, C.int(begin), C.int(end))
}

// Norm wraps double Quantum::Physics::PhonoEngine::Norm() const.
//
// Returns float64(0) if the wrapper has already been closed.
func (p *PhonoEngine) Norm() float64 {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return float64(0)
	}

	return float64(C.quantum_physics_PhonoEngine_Norm(p.handle))
}

// Normalize wraps void Quantum::Physics::PhonoEngine::Normalize().
//
// Does nothing if the wrapper has already been closed.
func (p *PhonoEngine) Normalize() {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return
	}

	C.quantum_physics_PhonoEngine_Normalize(p.handle)
}

// SetGaussianPacket wraps void Quantum::Physics::PhonoEngine::SetGaussianPacket(double, double, double, double, double, double, double, double, double).
//
// Does nothing if the wrapper has already been closed.
func (p *PhonoEngine) SetGaussianPacket(x0 float64, y0 float64, z0 float64, sx float64, sy float64, sz float64, kx float64, ky float64, kz float64) {
	p.mu.RLock()
	defer p.mu.RUnlock()
	// Keeps the wrapper reachable across the cgo call: without it the
	// collector may observe the last use of the receiver at the handle
	// load above and run the finalizer while C++ is still executing.
	defer runtime.KeepAlive(p)

	if p.handle == nil {
		return
	}

	C.quantum_physics_PhonoEngine_SetGaussianPacket(p.handle, C.double(x0), C.double(y0), C.double(z0), C.double(sx), C.double(sy), C.double(sz), C.double(kx), C.double(ky), C.double(kz))
}
