// Code generated by cppgo from the AST of Quantum::Physics::PhonoEngine. DO NOT EDIT.

#include "bridge.h"

#include <cstdlib>
#include <cstring>
#include <new>

#include "PhonoEngine.h"

extern "C" {

// Quantum::Physics::PhonoEngine::PhonoEngine(int, int, int, double, double, double, double, double, int)
PhonoEngineHandle quantum_physics_PhonoEngine_Create(int width, int height, int depth, double dx, double dy, double dz, double hbar, double mass, int max_workers) {
    // Explicit heap allocation; nothrow keeps C++ exceptions from
    // unwinding through the extern "C" frame into the Go runtime.
    return static_cast<PhonoEngineHandle>(new (std::nothrow) Quantum::Physics::PhonoEngine(width, height, depth, dx, dy, dz, hbar, mass, max_workers));
}

void quantum_physics_PhonoEngine_Destroy(PhonoEngineHandle handle) {
    delete static_cast<Quantum::Physics::PhonoEngine*>(handle);
}

// bool Quantum::Physics::PhonoEngine::Initialize()
unsigned char quantum_physics_PhonoEngine_Initialize(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0;
    }
    Quantum::Physics::PhonoEngine* self = static_cast<Quantum::Physics::PhonoEngine*>(handle);
    return static_cast<unsigned char>((self->Initialize()) ? 1 : 0);
}

// bool Quantum::Physics::PhonoEngine::Ready() const
unsigned char quantum_physics_PhonoEngine_Ready(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return static_cast<unsigned char>((self->Ready()) ? 1 : 0);
}

// int Quantum::Physics::PhonoEngine::Width() const
int quantum_physics_PhonoEngine_Width(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->Width();
}

// int Quantum::Physics::PhonoEngine::Height() const
int quantum_physics_PhonoEngine_Height(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->Height();
}

// int Quantum::Physics::PhonoEngine::Depth() const
int quantum_physics_PhonoEngine_Depth(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->Depth();
}

// int Quantum::Physics::PhonoEngine::Size() const
int quantum_physics_PhonoEngine_Size(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->Size();
}

// int Quantum::Physics::PhonoEngine::MaxWorkers() const
int quantum_physics_PhonoEngine_MaxWorkers(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->MaxWorkers();
}

// double Quantum::Physics::PhonoEngine::Dx() const
double quantum_physics_PhonoEngine_Dx(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0.0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->Dx();
}

// double Quantum::Physics::PhonoEngine::Dy() const
double quantum_physics_PhonoEngine_Dy(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0.0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->Dy();
}

// double Quantum::Physics::PhonoEngine::Dz() const
double quantum_physics_PhonoEngine_Dz(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0.0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->Dz();
}

// double Quantum::Physics::PhonoEngine::Hbar() const
double quantum_physics_PhonoEngine_Hbar(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0.0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->Hbar();
}

// double Quantum::Physics::PhonoEngine::Mass() const
double quantum_physics_PhonoEngine_Mass(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0.0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->Mass();
}

// double Quantum::Physics::PhonoEngine::CellVolume() const
double quantum_physics_PhonoEngine_CellVolume(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0.0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->CellVolume();
}

// size_t Quantum::Physics::PhonoEngine::PsiRealAddress() const
size_t quantum_physics_PhonoEngine_PsiRealAddress(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->PsiRealAddress();
}

// size_t Quantum::Physics::PhonoEngine::PsiImagAddress() const
size_t quantum_physics_PhonoEngine_PsiImagAddress(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->PsiImagAddress();
}

// size_t Quantum::Physics::PhonoEngine::PotentialAddress() const
size_t quantum_physics_PhonoEngine_PotentialAddress(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->PotentialAddress();
}

// size_t Quantum::Physics::PhonoEngine::DensityAddress() const
size_t quantum_physics_PhonoEngine_DensityAddress(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->DensityAddress();
}

// int Quantum::Physics::PhonoEngine::XLineCount() const
int quantum_physics_PhonoEngine_XLineCount(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->XLineCount();
}

// int Quantum::Physics::PhonoEngine::YBlockCount() const
int quantum_physics_PhonoEngine_YBlockCount(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->YBlockCount();
}

// int Quantum::Physics::PhonoEngine::ZBlockCount() const
int quantum_physics_PhonoEngine_ZBlockCount(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->ZBlockCount();
}

// void Quantum::Physics::PhonoEngine::PrepareStep(double)
void quantum_physics_PhonoEngine_PrepareStep(PhonoEngineHandle handle, double dt) {
    if (handle == nullptr) {
        return;
    }
    Quantum::Physics::PhonoEngine* self = static_cast<Quantum::Physics::PhonoEngine*>(handle);
    self->PrepareStep(dt);
}

// void Quantum::Physics::PhonoEngine::MarkPotentialDirty()
void quantum_physics_PhonoEngine_MarkPotentialDirty(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return;
    }
    Quantum::Physics::PhonoEngine* self = static_cast<Quantum::Physics::PhonoEngine*>(handle);
    self->MarkPotentialDirty();
}

// void Quantum::Physics::PhonoEngine::ApplyPotentialHalfStep(int, int)
void quantum_physics_PhonoEngine_ApplyPotentialHalfStep(PhonoEngineHandle handle, int begin, int end) {
    if (handle == nullptr) {
        return;
    }
    Quantum::Physics::PhonoEngine* self = static_cast<Quantum::Physics::PhonoEngine*>(handle);
    self->ApplyPotentialHalfStep(begin, end);
}

// void Quantum::Physics::PhonoEngine::SweepX(int, int, int)
void quantum_physics_PhonoEngine_SweepX(PhonoEngineHandle handle, int worker, int begin, int end) {
    if (handle == nullptr) {
        return;
    }
    Quantum::Physics::PhonoEngine* self = static_cast<Quantum::Physics::PhonoEngine*>(handle);
    self->SweepX(worker, begin, end);
}

// void Quantum::Physics::PhonoEngine::SweepY(int, int, int)
void quantum_physics_PhonoEngine_SweepY(PhonoEngineHandle handle, int worker, int begin, int end) {
    if (handle == nullptr) {
        return;
    }
    Quantum::Physics::PhonoEngine* self = static_cast<Quantum::Physics::PhonoEngine*>(handle);
    self->SweepY(worker, begin, end);
}

// void Quantum::Physics::PhonoEngine::SweepZ(int, int, int)
void quantum_physics_PhonoEngine_SweepZ(PhonoEngineHandle handle, int worker, int begin, int end) {
    if (handle == nullptr) {
        return;
    }
    Quantum::Physics::PhonoEngine* self = static_cast<Quantum::Physics::PhonoEngine*>(handle);
    self->SweepZ(worker, begin, end);
}

// void Quantum::Physics::PhonoEngine::StepTime(double)
void quantum_physics_PhonoEngine_StepTime(PhonoEngineHandle handle, double dt) {
    if (handle == nullptr) {
        return;
    }
    Quantum::Physics::PhonoEngine* self = static_cast<Quantum::Physics::PhonoEngine*>(handle);
    self->StepTime(dt);
}

// void Quantum::Physics::PhonoEngine::ComputeDensity(int, int)
void quantum_physics_PhonoEngine_ComputeDensity(PhonoEngineHandle handle, int begin, int end) {
    if (handle == nullptr) {
        return;
    }
    Quantum::Physics::PhonoEngine* self = static_cast<Quantum::Physics::PhonoEngine*>(handle);
    self->ComputeDensity(begin, end);
}

// double Quantum::Physics::PhonoEngine::Norm() const
double quantum_physics_PhonoEngine_Norm(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return 0.0;
    }
    const Quantum::Physics::PhonoEngine* self = static_cast<const Quantum::Physics::PhonoEngine*>(handle);
    return self->Norm();
}

// void Quantum::Physics::PhonoEngine::Normalize()
void quantum_physics_PhonoEngine_Normalize(PhonoEngineHandle handle) {
    if (handle == nullptr) {
        return;
    }
    Quantum::Physics::PhonoEngine* self = static_cast<Quantum::Physics::PhonoEngine*>(handle);
    self->Normalize();
}

// void Quantum::Physics::PhonoEngine::SetGaussianPacket(double, double, double, double, double, double, double, double, double)
void quantum_physics_PhonoEngine_SetGaussianPacket(PhonoEngineHandle handle, double x0, double y0, double z0, double sx, double sy, double sz, double kx, double ky, double kz) {
    if (handle == nullptr) {
        return;
    }
    Quantum::Physics::PhonoEngine* self = static_cast<Quantum::Physics::PhonoEngine*>(handle);
    self->SetGaussianPacket(x0, y0, z0, sx, sy, sz, kx, ky, kz);
}

}  // extern "C"
