/* Code generated by cppgo from the AST of Quantum::Physics::PhonoEngine. DO NOT EDIT. */

#ifndef CPPGO_QUANTUM_PHYSICS_PHONO_ENGINE_BRIDGE_H
#define CPPGO_QUANTUM_PHYSICS_PHONO_ENGINE_BRIDGE_H

#include <stddef.h>

/*
 * Boolean ABI contract: C++ `bool` crosses this boundary as an
 * `unsigned char`. Values produced by this library are always exactly
 * 0 (false) or 1 (true); values accepted treat any non-zero byte as true.
 */

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Opaque handle for Quantum::Physics::PhonoEngine.
 *
 * The C++ object is allocated on the native heap and never crosses into
 * the Go heap; Go only ever holds this pointer-sized token.
 */
typedef void* PhonoEngineHandle;

/* ---------------------------------------------------------------------
 * Lifecycle
 * ------------------------------------------------------------------- */

/* Quantum::Physics::PhonoEngine::PhonoEngine(int, int, int, double, double, double, double, double, int)
 * Returns NULL when the allocation fails. */
PhonoEngineHandle quantum_physics_PhonoEngine_Create(int width, int height, int depth, double dx, double dy, double dz, double hbar, double mass, int max_workers);

/* Releases a handle produced by quantum_physics_PhonoEngine_Create*(). Accepts NULL. */
void quantum_physics_PhonoEngine_Destroy(PhonoEngineHandle handle);

/* ---------------------------------------------------------------------
 * Methods
 * ------------------------------------------------------------------- */

/* bool Quantum::Physics::PhonoEngine::Initialize() */
unsigned char quantum_physics_PhonoEngine_Initialize(PhonoEngineHandle handle);

/* bool Quantum::Physics::PhonoEngine::Ready() const */
unsigned char quantum_physics_PhonoEngine_Ready(PhonoEngineHandle handle);

/* int Quantum::Physics::PhonoEngine::Width() const */
int quantum_physics_PhonoEngine_Width(PhonoEngineHandle handle);

/* int Quantum::Physics::PhonoEngine::Height() const */
int quantum_physics_PhonoEngine_Height(PhonoEngineHandle handle);

/* int Quantum::Physics::PhonoEngine::Depth() const */
int quantum_physics_PhonoEngine_Depth(PhonoEngineHandle handle);

/* int Quantum::Physics::PhonoEngine::Size() const */
int quantum_physics_PhonoEngine_Size(PhonoEngineHandle handle);

/* int Quantum::Physics::PhonoEngine::MaxWorkers() const */
int quantum_physics_PhonoEngine_MaxWorkers(PhonoEngineHandle handle);

/* double Quantum::Physics::PhonoEngine::Dx() const */
double quantum_physics_PhonoEngine_Dx(PhonoEngineHandle handle);

/* double Quantum::Physics::PhonoEngine::Dy() const */
double quantum_physics_PhonoEngine_Dy(PhonoEngineHandle handle);

/* double Quantum::Physics::PhonoEngine::Dz() const */
double quantum_physics_PhonoEngine_Dz(PhonoEngineHandle handle);

/* double Quantum::Physics::PhonoEngine::Hbar() const */
double quantum_physics_PhonoEngine_Hbar(PhonoEngineHandle handle);

/* double Quantum::Physics::PhonoEngine::Mass() const */
double quantum_physics_PhonoEngine_Mass(PhonoEngineHandle handle);

/* double Quantum::Physics::PhonoEngine::CellVolume() const */
double quantum_physics_PhonoEngine_CellVolume(PhonoEngineHandle handle);

/* size_t Quantum::Physics::PhonoEngine::PsiRealAddress() const */
size_t quantum_physics_PhonoEngine_PsiRealAddress(PhonoEngineHandle handle);

/* size_t Quantum::Physics::PhonoEngine::PsiImagAddress() const */
size_t quantum_physics_PhonoEngine_PsiImagAddress(PhonoEngineHandle handle);

/* size_t Quantum::Physics::PhonoEngine::PotentialAddress() const */
size_t quantum_physics_PhonoEngine_PotentialAddress(PhonoEngineHandle handle);

/* size_t Quantum::Physics::PhonoEngine::DensityAddress() const */
size_t quantum_physics_PhonoEngine_DensityAddress(PhonoEngineHandle handle);

/* int Quantum::Physics::PhonoEngine::XLineCount() const */
int quantum_physics_PhonoEngine_XLineCount(PhonoEngineHandle handle);

/* int Quantum::Physics::PhonoEngine::YBlockCount() const */
int quantum_physics_PhonoEngine_YBlockCount(PhonoEngineHandle handle);

/* int Quantum::Physics::PhonoEngine::ZBlockCount() const */
int quantum_physics_PhonoEngine_ZBlockCount(PhonoEngineHandle handle);

/* void Quantum::Physics::PhonoEngine::PrepareStep(double) */
void quantum_physics_PhonoEngine_PrepareStep(PhonoEngineHandle handle, double dt);

/* void Quantum::Physics::PhonoEngine::MarkPotentialDirty() */
void quantum_physics_PhonoEngine_MarkPotentialDirty(PhonoEngineHandle handle);

/* void Quantum::Physics::PhonoEngine::ApplyPotentialHalfStep(int, int) */
void quantum_physics_PhonoEngine_ApplyPotentialHalfStep(PhonoEngineHandle handle, int begin, int end);

/* void Quantum::Physics::PhonoEngine::SweepX(int, int, int) */
void quantum_physics_PhonoEngine_SweepX(PhonoEngineHandle handle, int worker, int begin, int end);

/* void Quantum::Physics::PhonoEngine::SweepY(int, int, int) */
void quantum_physics_PhonoEngine_SweepY(PhonoEngineHandle handle, int worker, int begin, int end);

/* void Quantum::Physics::PhonoEngine::SweepZ(int, int, int) */
void quantum_physics_PhonoEngine_SweepZ(PhonoEngineHandle handle, int worker, int begin, int end);

/* void Quantum::Physics::PhonoEngine::StepTime(double) */
void quantum_physics_PhonoEngine_StepTime(PhonoEngineHandle handle, double dt);

/* void Quantum::Physics::PhonoEngine::ComputeDensity(int, int) */
void quantum_physics_PhonoEngine_ComputeDensity(PhonoEngineHandle handle, int begin, int end);

/* double Quantum::Physics::PhonoEngine::Norm() const */
double quantum_physics_PhonoEngine_Norm(PhonoEngineHandle handle);

/* void Quantum::Physics::PhonoEngine::Normalize() */
void quantum_physics_PhonoEngine_Normalize(PhonoEngineHandle handle);

/* void Quantum::Physics::PhonoEngine::SetGaussianPacket(double, double, double, double, double, double, double, double, double) */
void quantum_physics_PhonoEngine_SetGaussianPacket(PhonoEngineHandle handle, double x0, double y0, double z0, double sx, double sy, double sz, double kx, double ky, double kz);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* CPPGO_QUANTUM_PHYSICS_PHONO_ENGINE_BRIDGE_H */
