// PhonoEngine.cpp -- Crank-Nicolson propagator for the 3D TDSE.
//
// =====================================================================
// THE CALCULUS, IN FULL
// =====================================================================
//
// -- 1. The equation ---------------------------------------------------
//
// The time-dependent Schrodinger equation is a first-order-in-time,
// second-order-in-space complex PDE:
//
//     i*hbar dPsi/dt = H Psi,   H = -(hbar^2/2m) (d2/dx2+d2/dy2+d2/dz2) + V
//
// H is Hermitian, so the exact propagator U(dt) = exp(-i H dt/hbar) is
// unitary: <Psi|Psi> is a conserved quantity. Any scheme worth using has
// to inherit that property, because |Psi|^2 is a probability density and
// a scheme that leaks norm is reporting that the particle is ceasing to
// exist.
//
// -- 2. Why Crank-Nicolson, and not forward Euler ----------------------
//
// Forward (explicit) Euler is Psi^{n+1} = (1 - i H dt/hbar) Psi^n. Its
// amplification factor for an eigenvalue E of H is |1 - iEdt/hbar| =
// sqrt(1 + (E dt/hbar)^2) > 1. Every mode grows. It is unconditionally
// *unstable* for this equation -- no dt saves it.
//
// Crank-Nicolson averages the spatial operator across the step, i.e. it
// applies the trapezoid rule to dPsi/dt = -(i/hbar) H Psi:
//
//     Psi^{n+1} = Psi^n - (i dt / 2hbar) H (Psi^n + Psi^{n+1})
//
// Group the unknowns on the left:
//
//     (I + i dt/(2hbar) H) Psi^{n+1} = (I - i dt/(2hbar) H) Psi^n   (*)
//
// This is the Cayley transform of H. Its amplification factor is
//
//     (1 - iEdt/2hbar) / (1 + iEdt/2hbar)
//
// a ratio of a complex number to its own conjugate, so its modulus is
// exactly 1 for every eigenvalue E and every dt. The scheme is
// unconditionally stable AND exactly unitary -- norm is conserved to
// rounding error, not merely to truncation order. Expanding both sides
// shows it matches exp(-iHdt/hbar) through the dt^2 term, so it is
// second-order accurate in time.
//
// The price is the word "implicit": (*) is a linear *system*. In 3D the
// matrix I + i dt/(2hbar) H is N x N with N = W*H*D and a seven-point
// stencil. Solving that directly, per step, is what the rest of this
// file is about avoiding.
//
// -- 3. Operator splitting: how a 3D implicit solve becomes 1D ---------
//
// Split the Hamiltonian along the axes:
//
//     H = V + Tx + Ty + Tz,   Td = -(hbar^2/2m) d2/d(axis)^2
//
// Each piece is separately Hermitian, so the Cayley transform of each is
// separately unitary. Compose them symmetrically (Strang splitting):
//
//     U(dt) ~= V(dt/2) X(dt/2) Y(dt/2) Z(dt) Y(dt/2) X(dt/2) V(dt/2)
//
// A palindromic composition of second-order-accurate factors is itself
// second-order accurate: the first-order commutator error [A,B]dt^2/2
// generated by the forward half cancels against the one generated by the
// reverse half. (Applying X, Y, Z once each in a fixed order would leave
// that term uncancelled and drop the scheme to first order.) Because
// every factor is unitary, so is the product -- the splitting costs
// accuracy, never stability and never norm.
//
// The payoff: Td involves only one axis, so its Cayley system decouples
// into independent tridiagonal systems, one per grid line along that
// axis. Each is solved in O(n) by the Thomas algorithm, and the lines
// are mutually independent, which is exactly the shape that shards
// across cores.
//
// -- 4. The 1D system, discretised -------------------------------------
//
// Central second difference on a uniform grid of spacing h:
//
//     d2Psi/dx2 |_j = (Psi_{j-1} - 2 Psi_j + Psi_{j+1}) / h^2 + O(h^2)
//
// so with alpha = -hbar^2/(2 m h^2), Td Psi_j = alpha(Psi_{j-1} - 2Psi_j
// + Psi_{j+1}). Substituting into (*) with step tau and writing
// lambda = i tau alpha / (2 hbar) = -i * tau*hbar/(4 m h^2), define
//
//     r = tau * hbar / (4 * m * h^2)     so lambda = -i r
//
// The row j of the system is then
//
//     -i r Psi*_{j-1} + (1 + 2 i r) Psi*_j - i r Psi*_{j+1}
//         = Psi_j + i r (Psi_{j-1} - 2 Psi_j + Psi_{j+1})
//
// A constant-coefficient complex tridiagonal system: sub- and
// super-diagonal a = c = -i r, diagonal b = 1 + 2 i r, right-hand side
// the explicit half of the same stencil. Dirichlet walls mean the ghost
// values at j = -1 and j = n vanish, so all n points are unknowns.
//
// Splitting into real (u) and imaginary (v) parts, with
// Lu_j = u_{j-1} - 2u_j + u_{j+1}:
//
//     d_re_j = u_j - r * Lv_j
//     d_im_j = v_j + r * Lu_j
//
// -- 5. Thomas, with the factorisation hoisted out of the loop ---------
//
// Forward elimination:
//     w_0 = 1/b,             cp_0 = c * w_0,        dp_0 = d_0 * w_0
//     w_j = 1/(b - a cp_{j-1}), cp_j = c * w_j,
//     dp_j = (d_j - a dp_{j-1}) * w_j
// Back substitution:
//     x_{n-1} = dp_{n-1},    x_j = dp_j - cp_j x_{j+1}
//
// a, b and c do not depend on j or on which line is being solved, so
// {w_j, cp_j} depend only on the axis length and on r. They are computed
// once per PrepareStep() and reused across all Height*Depth lines --
// turning the per-line cost into two multiply-add passes.
//
// -- 6. The diagonal factor --------------------------------------------
//
// V is diagonal, so its exact propagator is a pointwise phase rotation
// exp(-i V tau / hbar) -- no linear solve, no Cayley approximation
// needed, and exactly unitary. For a static V and fixed dt the phase is
// constant in time, so cos and sin are tabulated in PrepareStep() and
// the half-step degenerates to a 2x2 rotation per grid point.
//
// =====================================================================

#include "PhonoEngine.h"

#include <cmath>
#include <cstring>
#include <new>

namespace Quantum {
namespace Physics {
namespace {

// Rounds a byte count up to a whole number of cache lines.
std::size_t PadToCacheLine(std::size_t bytes) noexcept {
    const std::size_t mask = kCacheLineBytes - 1;
    return (bytes + mask) & ~mask;
}

// Computes one row of the Crank-Nicolson right-hand side for a block of
// kLaneWidth-adjacent lines.
//
// HasPrev/HasNext are template parameters rather than runtime branches so
// that the boundary rows are peeled out of the interior loop entirely:
// the body below contains no conditionals and no loop-carried dependency
// in l, which is what lets the vectoriser turn it into unit-stride SIMD
// loads and fused multiply-adds.
template <bool HasPrev, bool HasNext>
inline void RhsRow(const double* __restrict u, const double* __restrict v,
                   std::size_t idx, std::size_t stride, int lanes, double r,
                   double* __restrict d_re, double* __restrict d_im) noexcept {
    for (int l = 0; l < lanes; ++l) {
        const double u0 = u[idx + l];
        const double v0 = v[idx + l];
        const double um = HasPrev ? u[idx + l - stride] : 0.0;
        const double vm = HasPrev ? v[idx + l - stride] : 0.0;
        const double up = HasNext ? u[idx + l + stride] : 0.0;
        const double vp = HasNext ? v[idx + l + stride] : 0.0;
        // Central second difference, numerator only; the 1/h^2 is folded
        // into r.
        const double lap_u = um - 2.0 * u0 + up;
        const double lap_v = vm - 2.0 * v0 + vp;
        // d = Psi + i r (Laplacian Psi); multiplying by i swaps the parts
        // and negates the new real component.
        d_re[l] = u0 - r * lap_v;
        d_im[l] = v0 + r * lap_u;
    }
}

}  // namespace

// ---------------------------------------------------------------------
// Lifecycle
// ---------------------------------------------------------------------

PhonoEngine::PhonoEngine(int width, int height, int depth,
                         double dx, double dy, double dz,
                         double hbar, double mass,
                         int max_workers) noexcept
    : width_(width > 0 ? width : 0),
      height_(height > 0 ? height : 0),
      depth_(depth > 0 ? depth : 0),
      size_(0),
      max_workers_(max_workers > 0 ? max_workers : 1),
      dx_(dx),
      dy_(dy),
      dz_(dz),
      hbar_(hbar),
      mass_(mass) {
    // Computed rather than assigned in the member list so the clamped
    // extents above are the ones multiplied.
    size_ = width_ * height_ * depth_;
}

PhonoEngine::~PhonoEngine() {
    ::operator delete(scratch_, std::align_val_t(kCacheLineBytes));
    scratch_ = nullptr;
}

bool PhonoEngine::Initialize() noexcept {
    if (ready_) {
        return true;
    }
    if (size_ <= 0 || dx_ <= 0.0 || dy_ <= 0.0 || dz_ <= 0.0 ||
        hbar_ <= 0.0 || mass_ <= 0.0) {
        return false;
    }

    // std::vector reports exhaustion by throwing. An exception must not
    // cross the extern "C" bridge frame into the Go runtime, so it is
    // caught here and reported as a bool, mirroring the `new
    // (std::nothrow)` discipline the generated bridge uses for the object
    // itself.
    try {
        const std::size_t n = static_cast<std::size_t>(size_);
        psi_real_.assign(n, 0.0);
        psi_imag_.assign(n, 0.0);
        potential_.assign(n, 0.0);
        density_.assign(n, 0.0);
        phase_cos_.assign(n, 1.0);
        phase_sin_.assign(n, 0.0);

        fx_.cp_re.assign(static_cast<std::size_t>(width_), 0.0);
        fx_.cp_im.assign(static_cast<std::size_t>(width_), 0.0);
        fx_.w_re.assign(static_cast<std::size_t>(width_), 0.0);
        fx_.w_im.assign(static_cast<std::size_t>(width_), 0.0);

        fy_.cp_re.assign(static_cast<std::size_t>(height_), 0.0);
        fy_.cp_im.assign(static_cast<std::size_t>(height_), 0.0);
        fy_.w_re.assign(static_cast<std::size_t>(height_), 0.0);
        fy_.w_im.assign(static_cast<std::size_t>(height_), 0.0);

        fz_.cp_re.assign(static_cast<std::size_t>(depth_), 0.0);
        fz_.cp_im.assign(static_cast<std::size_t>(depth_), 0.0);
        fz_.w_re.assign(static_cast<std::size_t>(depth_), 0.0);
        fz_.w_im.assign(static_cast<std::size_t>(depth_), 0.0);
    } catch (...) {
        return false;
    }

    // Scratch holds the forward-elimination vector dp for one blocked
    // solve: the longest axis, times the lane width, times two for the
    // real and imaginary parts. Each worker's slab starts on its own
    // cache line, so two cores sweeping different lines never contend for
    // one line's ownership.
    int longest = width_;
    if (height_ > longest) longest = height_;
    if (depth_ > longest) longest = depth_;

    const std::size_t slab_doubles =
        static_cast<std::size_t>(longest) * kLaneWidth * 2u;
    const std::size_t slab_bytes = PadToCacheLine(slab_doubles * sizeof(double));
    scratch_stride_ = slab_bytes / sizeof(double);

    const std::size_t total = scratch_stride_ *
                              static_cast<std::size_t>(max_workers_) *
                              sizeof(double);
    scratch_ = static_cast<double*>(::operator new(
        total, std::align_val_t(kCacheLineBytes), std::nothrow));
    if (scratch_ == nullptr) {
        return false;
    }
    std::memset(scratch_, 0, total);

    ready_ = true;
    return true;
}

bool PhonoEngine::Ready() const noexcept { return ready_; }

// ---------------------------------------------------------------------
// Geometry
// ---------------------------------------------------------------------

int PhonoEngine::Width() const noexcept { return width_; }
int PhonoEngine::Height() const noexcept { return height_; }
int PhonoEngine::Depth() const noexcept { return depth_; }
int PhonoEngine::Size() const noexcept { return size_; }
int PhonoEngine::MaxWorkers() const noexcept { return max_workers_; }
double PhonoEngine::Dx() const noexcept { return dx_; }
double PhonoEngine::Dy() const noexcept { return dy_; }
double PhonoEngine::Dz() const noexcept { return dz_; }
double PhonoEngine::Hbar() const noexcept { return hbar_; }
double PhonoEngine::Mass() const noexcept { return mass_; }
double PhonoEngine::CellVolume() const noexcept { return dx_ * dy_ * dz_; }

size_t PhonoEngine::PsiRealAddress() const noexcept {
    return reinterpret_cast<size_t>(psi_real_.data());
}
size_t PhonoEngine::PsiImagAddress() const noexcept {
    return reinterpret_cast<size_t>(psi_imag_.data());
}
size_t PhonoEngine::PotentialAddress() const noexcept {
    return reinterpret_cast<size_t>(potential_.data());
}
size_t PhonoEngine::DensityAddress() const noexcept {
    return reinterpret_cast<size_t>(density_.data());
}

int PhonoEngine::XLineCount() const noexcept { return height_ * depth_; }

int PhonoEngine::YBlockCount() const noexcept {
    const int blocks = (width_ + kLaneWidth - 1) / kLaneWidth;
    return depth_ * blocks;
}

int PhonoEngine::ZBlockCount() const noexcept {
    const int blocks = (width_ + kLaneWidth - 1) / kLaneWidth;
    return height_ * blocks;
}

double* PhonoEngine::WorkerScratch(int worker) const noexcept {
    if (worker < 0 || worker >= max_workers_) {
        worker = 0;
    }
    return scratch_ + scratch_stride_ * static_cast<std::size_t>(worker);
}

// ---------------------------------------------------------------------
// Preparation
// ---------------------------------------------------------------------

void PhonoEngine::BuildFactors(TridiagFactors& f, int n, double h,
                               double tau) noexcept {
    // r = tau*hbar / (4 m h^2); see derivation section 4.
    const double r = tau * hbar_ / (4.0 * mass_ * h * h);
    f.r = r;

    // a = c = (0, -r); b = (1, 2r).
    //
    // Row 0: w_0 = 1/b. The reciprocal of (br, bi) is
    // (br, -bi)/(br^2+bi^2).
    {
        const double br = 1.0;
        const double bi = 2.0 * r;
        const double inv = 1.0 / (br * br + bi * bi);
        const double wr = br * inv;
        const double wi = -bi * inv;
        f.w_re[0] = wr;
        f.w_im[0] = wi;
        // cp_0 = c*w_0 = (0,-r)*(wr,wi) = (r*wi, -r*wr).
        f.cp_re[0] = r * wi;
        f.cp_im[0] = -r * wr;
    }

    for (int j = 1; j < n; ++j) {
        // denom = b - a*cp_{j-1}. With a = (0,-r):
        //   a*cp = (0,-r)*(cr,ci) = (r*ci, -r*cr)
        const double cr = f.cp_re[j - 1];
        const double ci = f.cp_im[j - 1];
        const double dr = 1.0 - r * ci;
        const double di = 2.0 * r + r * cr;

        const double inv = 1.0 / (dr * dr + di * di);
        const double wr = dr * inv;
        const double wi = -di * inv;
        f.w_re[j] = wr;
        f.w_im[j] = wi;
        f.cp_re[j] = r * wi;
        f.cp_im[j] = -r * wr;
    }
}

void PhonoEngine::MarkPotentialDirty() noexcept { potential_dirty_ = true; }

void PhonoEngine::PrepareStep(double dt) noexcept {
    if (!ready_) {
        return;
    }
    const bool dt_changed = (dt != prepared_dt_);
    if (!dt_changed && !potential_dirty_) {
        return;
    }

    if (dt_changed) {
        // The Strang composition applies x and y with tau = dt/2 (twice
        // each) and z with tau = dt (once).
        BuildFactors(fx_, width_, dx_, 0.5 * dt);
        BuildFactors(fy_, height_, dy_, 0.5 * dt);
        BuildFactors(fz_, depth_, dz_, dt);
        prepared_dt_ = dt;
    }

    // Diagonal half-step phase: Psi <- exp(-i V dt/(2 hbar)) Psi. Static V
    // and fixed dt make this constant in time, so the transcendentals are
    // paid once here rather than Size() times per step.
    const double scale = -0.5 * dt / hbar_;
    for (int i = 0; i < size_; ++i) {
        const double theta = potential_[i] * scale;
        phase_cos_[i] = std::cos(theta);
        phase_sin_[i] = std::sin(theta);
    }
    potential_dirty_ = false;
}

// ---------------------------------------------------------------------
// Phase 1/7: the diagonal (potential) half-step
// ---------------------------------------------------------------------

void PhonoEngine::ApplyPotentialHalfStep(int begin, int end) noexcept {
    if (!ready_) {
        return;
    }
    if (begin < 0) begin = 0;
    if (end > size_) end = size_;

    double* __restrict u = psi_real_.data();
    double* __restrict v = psi_imag_.data();
    const double* __restrict c = phase_cos_.data();
    const double* __restrict s = phase_sin_.data();

    // (c + i s)(u + i v) = (uc - vs) + i(us + vc): a plane rotation of the
    // (Re, Im) pair by the tabulated angle. Pointwise, no dependencies --
    // this is the most trivially vectorisable loop in the engine.
    for (int i = begin; i < end; ++i) {
        const double ur = u[i];
        const double vr = v[i];
        u[i] = ur * c[i] - vr * s[i];
        v[i] = ur * s[i] + vr * c[i];
    }
}

// ---------------------------------------------------------------------
// Phase 2/6: Cayley solve along x
// ---------------------------------------------------------------------
//
// x is the unit-stride axis, so a line is contiguous. The Thomas
// recurrence is inherently serial along the line, and vectorising across
// lines here would mean gathering at stride Width -- so this variant runs
// one line at a time and takes its parallelism from the shard split
// instead, which is the right trade when the line itself is contiguous
// and prefetch-friendly.

void PhonoEngine::SweepX(int worker, int begin, int end) noexcept {
    if (!ready_) {
        return;
    }
    const int lines = XLineCount();
    if (begin < 0) begin = 0;
    if (end > lines) end = lines;

    const int n = width_;
    if (n <= 0) {
        return;
    }

    double* __restrict u = psi_real_.data();
    double* __restrict v = psi_imag_.data();
    const double r = fx_.r;
    const double* __restrict cp_re = fx_.cp_re.data();
    const double* __restrict cp_im = fx_.cp_im.data();
    const double* __restrict w_re = fx_.w_re.data();
    const double* __restrict w_im = fx_.w_im.data();

    double* __restrict dp_re = WorkerScratch(worker);
    double* __restrict dp_im = dp_re + static_cast<std::size_t>(n);

    for (int line = begin; line < end; ++line) {
        const int z = line / height_;
        const int y = line - z * height_;
        const std::size_t base =
            (static_cast<std::size_t>(z) * height_ + y) * width_;

        // ---- forward elimination, fused with RHS construction --------
        // dp_0 = d_0 * w_0
        {
            const double u0 = u[base];
            const double v0 = v[base];
            const double up = (n > 1) ? u[base + 1] : 0.0;
            const double vp = (n > 1) ? v[base + 1] : 0.0;
            const double lap_u = -2.0 * u0 + up;   // ghost wall at j = -1
            const double lap_v = -2.0 * v0 + vp;
            const double d_re = u0 - r * lap_v;
            const double d_im = v0 + r * lap_u;
            dp_re[0] = d_re * w_re[0] - d_im * w_im[0];
            dp_im[0] = d_re * w_im[0] + d_im * w_re[0];
        }

        for (int j = 1; j < n; ++j) {
            const std::size_t idx = base + j;
            const double u0 = u[idx];
            const double v0 = v[idx];
            const double um = u[idx - 1];
            const double vm = v[idx - 1];
            const double up = (j + 1 < n) ? u[idx + 1] : 0.0;
            const double vp = (j + 1 < n) ? v[idx + 1] : 0.0;
            const double lap_u = um - 2.0 * u0 + up;
            const double lap_v = vm - 2.0 * v0 + vp;
            const double d_re = u0 - r * lap_v;
            const double d_im = v0 + r * lap_u;

            // t = d_j - a*dp_{j-1}, with a = (0,-r):
            //   a*dp = (r*dp_im, -r*dp_re)
            const double t_re = d_re - r * dp_im[j - 1];
            const double t_im = d_im + r * dp_re[j - 1];
            // dp_j = t * w_j
            dp_re[j] = t_re * w_re[j] - t_im * w_im[j];
            dp_im[j] = t_re * w_im[j] + t_im * w_re[j];
        }

        // ---- back substitution --------------------------------------
        double x_re = dp_re[n - 1];
        double x_im = dp_im[n - 1];
        u[base + n - 1] = x_re;
        v[base + n - 1] = x_im;
        for (int j = n - 2; j >= 0; --j) {
            // x_j = dp_j - cp_j * x_{j+1}
            const double pr = cp_re[j] * x_re - cp_im[j] * x_im;
            const double pi = cp_re[j] * x_im + cp_im[j] * x_re;
            x_re = dp_re[j] - pr;
            x_im = dp_im[j] - pi;
            u[base + j] = x_re;
            v[base + j] = x_im;
        }
    }
}

// ---------------------------------------------------------------------
// Phase 3/5 and 4: Cayley solves along y and z
// ---------------------------------------------------------------------
//
// Along y and z a line is strided (Width, and Width*Height). Solving one
// such line at a time would touch one double per cache line. Instead each
// unit of work carries kLaneWidth *adjacent x values* through the
// recurrence together: the inner loop over lanes is unit-stride and
// dependency-free, so it vectorises, and every cache line loaded is fully
// consumed.

void PhonoEngine::SweepY(int worker, int begin, int end) noexcept {
    if (!ready_) {
        return;
    }
    const int blocks_per_plane = (width_ + kLaneWidth - 1) / kLaneWidth;
    const int units = depth_ * blocks_per_plane;
    if (begin < 0) begin = 0;
    if (end > units) end = units;

    const int n = height_;
    if (n <= 0) {
        return;
    }
    const std::size_t stride = static_cast<std::size_t>(width_);

    double* __restrict u = psi_real_.data();
    double* __restrict v = psi_imag_.data();
    const double r = fy_.r;
    const double* __restrict cp_re = fy_.cp_re.data();
    const double* __restrict cp_im = fy_.cp_im.data();
    const double* __restrict w_re = fy_.w_re.data();
    const double* __restrict w_im = fy_.w_im.data();

    double* __restrict scratch = WorkerScratch(worker);
    double* __restrict dp_re = scratch;
    double* __restrict dp_im = scratch + static_cast<std::size_t>(n) * kLaneWidth;

    double row_re[kLaneWidth];
    double row_im[kLaneWidth];

    for (int unit = begin; unit < end; ++unit) {
        const int z = unit / blocks_per_plane;
        const int bx = unit - z * blocks_per_plane;
        const int x0 = bx * kLaneWidth;
        int lanes = width_ - x0;
        if (lanes > kLaneWidth) lanes = kLaneWidth;
        if (lanes <= 0) continue;

        const std::size_t base =
            static_cast<std::size_t>(z) * height_ * width_ + x0;

        // ---- j = 0: no predecessor row --------------------------------
        // A one-cell axis has no successor row either: the walls sit on
        // both sides of the single unknown, so the <false,false> form is
        // the one that stays in bounds.
        if (n > 1) {
            RhsRow<false, true>(u, v, base, stride, lanes, r, row_re, row_im);
        } else {
            RhsRow<false, false>(u, v, base, stride, lanes, r, row_re, row_im);
        }
        for (int l = 0; l < lanes; ++l) {
            dp_re[l] = row_re[l] * w_re[0] - row_im[l] * w_im[0];
            dp_im[l] = row_re[l] * w_im[0] + row_im[l] * w_re[0];
        }

        // ---- interior rows --------------------------------------------
        for (int j = 1; j < n - 1; ++j) {
            const std::size_t idx = base + static_cast<std::size_t>(j) * stride;
            RhsRow<true, true>(u, v, idx, stride, lanes, r, row_re, row_im);
            const double wr = w_re[j];
            const double wi = w_im[j];
            const std::size_t off = static_cast<std::size_t>(j) * kLaneWidth;
            const std::size_t prev = off - kLaneWidth;
            for (int l = 0; l < lanes; ++l) {
                const double t_re = row_re[l] - r * dp_im[prev + l];
                const double t_im = row_im[l] + r * dp_re[prev + l];
                dp_re[off + l] = t_re * wr - t_im * wi;
                dp_im[off + l] = t_re * wi + t_im * wr;
            }
        }

        // ---- j = n-1: no successor row ---------------------------------
        if (n > 1) {
            const int j = n - 1;
            const std::size_t idx = base + static_cast<std::size_t>(j) * stride;
            RhsRow<true, false>(u, v, idx, stride, lanes, r, row_re, row_im);
            const double wr = w_re[j];
            const double wi = w_im[j];
            const std::size_t off = static_cast<std::size_t>(j) * kLaneWidth;
            const std::size_t prev = off - kLaneWidth;
            for (int l = 0; l < lanes; ++l) {
                const double t_re = row_re[l] - r * dp_im[prev + l];
                const double t_im = row_im[l] + r * dp_re[prev + l];
                dp_re[off + l] = t_re * wr - t_im * wi;
                dp_im[off + l] = t_re * wi + t_im * wr;
            }
        }

        // ---- back substitution -----------------------------------------
        {
            const std::size_t off = static_cast<std::size_t>(n - 1) * kLaneWidth;
            const std::size_t idx =
                base + static_cast<std::size_t>(n - 1) * stride;
            for (int l = 0; l < lanes; ++l) {
                u[idx + l] = dp_re[off + l];
                v[idx + l] = dp_im[off + l];
            }
        }
        for (int j = n - 2; j >= 0; --j) {
            const std::size_t off = static_cast<std::size_t>(j) * kLaneWidth;
            const std::size_t idx = base + static_cast<std::size_t>(j) * stride;
            const std::size_t nxt = idx + stride;
            const double cr = cp_re[j];
            const double ci = cp_im[j];
            for (int l = 0; l < lanes; ++l) {
                const double xr = u[nxt + l];
                const double xi = v[nxt + l];
                u[idx + l] = dp_re[off + l] - (cr * xr - ci * xi);
                v[idx + l] = dp_im[off + l] - (cr * xi + ci * xr);
            }
        }
    }
}

void PhonoEngine::SweepZ(int worker, int begin, int end) noexcept {
    if (!ready_) {
        return;
    }
    const int blocks_per_plane = (width_ + kLaneWidth - 1) / kLaneWidth;
    const int units = height_ * blocks_per_plane;
    if (begin < 0) begin = 0;
    if (end > units) end = units;

    const int n = depth_;
    if (n <= 0) {
        return;
    }
    const std::size_t stride =
        static_cast<std::size_t>(width_) * static_cast<std::size_t>(height_);

    double* __restrict u = psi_real_.data();
    double* __restrict v = psi_imag_.data();
    const double r = fz_.r;
    const double* __restrict cp_re = fz_.cp_re.data();
    const double* __restrict cp_im = fz_.cp_im.data();
    const double* __restrict w_re = fz_.w_re.data();
    const double* __restrict w_im = fz_.w_im.data();

    double* __restrict scratch = WorkerScratch(worker);
    double* __restrict dp_re = scratch;
    double* __restrict dp_im = scratch + static_cast<std::size_t>(n) * kLaneWidth;

    double row_re[kLaneWidth];
    double row_im[kLaneWidth];

    for (int unit = begin; unit < end; ++unit) {
        const int y = unit / blocks_per_plane;
        const int bx = unit - y * blocks_per_plane;
        const int x0 = bx * kLaneWidth;
        int lanes = width_ - x0;
        if (lanes > kLaneWidth) lanes = kLaneWidth;
        if (lanes <= 0) continue;

        const std::size_t base =
            static_cast<std::size_t>(y) * width_ + x0;

        // A one-cell axis has no successor row either: the walls sit on
        // both sides of the single unknown, so the <false,false> form is
        // the one that stays in bounds.
        if (n > 1) {
            RhsRow<false, true>(u, v, base, stride, lanes, r, row_re, row_im);
        } else {
            RhsRow<false, false>(u, v, base, stride, lanes, r, row_re, row_im);
        }
        for (int l = 0; l < lanes; ++l) {
            dp_re[l] = row_re[l] * w_re[0] - row_im[l] * w_im[0];
            dp_im[l] = row_re[l] * w_im[0] + row_im[l] * w_re[0];
        }

        for (int j = 1; j < n - 1; ++j) {
            const std::size_t idx = base + static_cast<std::size_t>(j) * stride;
            RhsRow<true, true>(u, v, idx, stride, lanes, r, row_re, row_im);
            const double wr = w_re[j];
            const double wi = w_im[j];
            const std::size_t off = static_cast<std::size_t>(j) * kLaneWidth;
            const std::size_t prev = off - kLaneWidth;
            for (int l = 0; l < lanes; ++l) {
                const double t_re = row_re[l] - r * dp_im[prev + l];
                const double t_im = row_im[l] + r * dp_re[prev + l];
                dp_re[off + l] = t_re * wr - t_im * wi;
                dp_im[off + l] = t_re * wi + t_im * wr;
            }
        }

        if (n > 1) {
            const int j = n - 1;
            const std::size_t idx = base + static_cast<std::size_t>(j) * stride;
            RhsRow<true, false>(u, v, idx, stride, lanes, r, row_re, row_im);
            const double wr = w_re[j];
            const double wi = w_im[j];
            const std::size_t off = static_cast<std::size_t>(j) * kLaneWidth;
            const std::size_t prev = off - kLaneWidth;
            for (int l = 0; l < lanes; ++l) {
                const double t_re = row_re[l] - r * dp_im[prev + l];
                const double t_im = row_im[l] + r * dp_re[prev + l];
                dp_re[off + l] = t_re * wr - t_im * wi;
                dp_im[off + l] = t_re * wi + t_im * wr;
            }
        }

        {
            const std::size_t off = static_cast<std::size_t>(n - 1) * kLaneWidth;
            const std::size_t idx =
                base + static_cast<std::size_t>(n - 1) * stride;
            for (int l = 0; l < lanes; ++l) {
                u[idx + l] = dp_re[off + l];
                v[idx + l] = dp_im[off + l];
            }
        }
        for (int j = n - 2; j >= 0; --j) {
            const std::size_t off = static_cast<std::size_t>(j) * kLaneWidth;
            const std::size_t idx = base + static_cast<std::size_t>(j) * stride;
            const std::size_t nxt = idx + stride;
            const double cr = cp_re[j];
            const double ci = cp_im[j];
            for (int l = 0; l < lanes; ++l) {
                const double xr = u[nxt + l];
                const double xi = v[nxt + l];
                u[idx + l] = dp_re[off + l] - (cr * xr - ci * xi);
                v[idx + l] = dp_im[off + l] - (cr * xi + ci * xr);
            }
        }
    }
}

// ---------------------------------------------------------------------
// Serial driver
// ---------------------------------------------------------------------

void PhonoEngine::StepTime(double dt) noexcept {
    if (!ready_) {
        return;
    }
    PrepareStep(dt);

    const int n = size_;
    const int xl = XLineCount();
    const int yb = YBlockCount();
    const int zb = ZBlockCount();

    // The palindrome from section 3. Reading it aloud is the algorithm:
    // half a kick, half a drift in x, half in y, a full drift in z, then
    // unwind the same sequence in reverse.
    ApplyPotentialHalfStep(0, n);
    SweepX(0, 0, xl);
    SweepY(0, 0, yb);
    SweepZ(0, 0, zb);
    SweepY(0, 0, yb);
    SweepX(0, 0, xl);
    ApplyPotentialHalfStep(0, n);
}

// ---------------------------------------------------------------------
// Observables
// ---------------------------------------------------------------------

void PhonoEngine::ComputeDensity(int begin, int end) noexcept {
    if (!ready_) {
        return;
    }
    if (begin < 0) begin = 0;
    if (end > size_) end = size_;

    const double* __restrict u = psi_real_.data();
    const double* __restrict v = psi_imag_.data();
    double* __restrict d = density_.data();
    for (int i = begin; i < end; ++i) {
        d[i] = u[i] * u[i] + v[i] * v[i];
    }
}

double PhonoEngine::Norm() const noexcept {
    if (!ready_) {
        return 0.0;
    }
    const double* __restrict u = psi_real_.data();
    const double* __restrict v = psi_imag_.data();

    // Four partial sums: floating-point addition is not associative, so
    // this both shortens the dependency chain for the pipeline and keeps
    // the rounding error growing like sqrt(N/4) instead of N.
    double s0 = 0.0, s1 = 0.0, s2 = 0.0, s3 = 0.0;
    int i = 0;
    for (; i + 3 < size_; i += 4) {
        s0 += u[i] * u[i] + v[i] * v[i];
        s1 += u[i + 1] * u[i + 1] + v[i + 1] * v[i + 1];
        s2 += u[i + 2] * u[i + 2] + v[i + 2] * v[i + 2];
        s3 += u[i + 3] * u[i + 3] + v[i + 3] * v[i + 3];
    }
    for (; i < size_; ++i) {
        s0 += u[i] * u[i] + v[i] * v[i];
    }
    return ((s0 + s1) + (s2 + s3)) * CellVolume();
}

void PhonoEngine::Normalize() noexcept {
    if (!ready_) {
        return;
    }
    const double norm = Norm();
    if (!(norm > 0.0)) {
        return;
    }
    const double scale = 1.0 / std::sqrt(norm);
    double* __restrict u = psi_real_.data();
    double* __restrict v = psi_imag_.data();
    for (int i = 0; i < size_; ++i) {
        u[i] *= scale;
        v[i] *= scale;
    }
}

void PhonoEngine::SetGaussianPacket(double x0, double y0, double z0,
                                    double sx, double sy, double sz,
                                    double kx, double ky, double kz) noexcept {
    if (!ready_) {
        return;
    }
    if (!(sx > 0.0) || !(sy > 0.0) || !(sz > 0.0)) {
        return;
    }

    const double inv_2sx2 = 1.0 / (2.0 * sx * sx);
    const double inv_2sy2 = 1.0 / (2.0 * sy * sy);
    const double inv_2sz2 = 1.0 / (2.0 * sz * sz);

    double* __restrict u = psi_real_.data();
    double* __restrict v = psi_imag_.data();

    for (int z = 0; z < depth_; ++z) {
        // Grid point i sits at (i+1)*h: the Dirichlet walls occupy the
        // ghost slots at index -1 and index n.
        const double zc = (static_cast<double>(z) + 1.0) * dz_;
        const double dzr = zc - z0;
        const double gz = dzr * dzr * inv_2sz2;
        for (int y = 0; y < height_; ++y) {
            const double yc = (static_cast<double>(y) + 1.0) * dy_;
            const double dyr = yc - y0;
            const double gy = dyr * dyr * inv_2sy2;
            const std::size_t row =
                (static_cast<std::size_t>(z) * height_ + y) * width_;
            for (int x = 0; x < width_; ++x) {
                const double xc = (static_cast<double>(x) + 1.0) * dx_;
                const double dxr = xc - x0;
                const double gx = dxr * dxr * inv_2sx2;

                const double envelope = std::exp(-(gx + gy + gz));
                const double phase = kx * xc + ky * yc + kz * zc;
                u[row + x] = envelope * std::cos(phase);
                v[row + x] = envelope * std::sin(phase);
            }
        }
    }
    Normalize();
}

}  // namespace Physics
}  // namespace Quantum
